# Generated by Django 3.0.8 on 2020-08-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('food_energy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('photo', models.ImageField(null=True, upload_to='uploads/dishes')),
                ('price', models.FloatField()),
                ('dish_calories', models.FloatField()),
                ('ingredients', models.ManyToManyField(to='restaurants.Ingredient')),
            ],
        ),
    ]
