# Generated by Django 3.0.8 on 2020-08-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20200803_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='dishes',
            field=models.ManyToManyField(to='restaurants.Dish'),
        ),
    ]
