# Generated by Django 3.0.8 on 2020-08-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurant_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='food_energy',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
