# Generated by Django 3.0.8 on 2020-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20200805_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_calories',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
