# Generated by Django 3.0.8 on 2020-08-06 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0013_auto_20200805_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_calories',
            field=models.DecimalField(decimal_places=2, help_text='Обязательное. Калорийность блюда', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(help_text='Обязательное. Список ингредиентов блюда', to='restaurants.Ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(help_text='Обязательное. Название блюда', max_length=128),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(help_text='Фотография блюда', null=True, upload_to='uploads/dishes'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Обязательное. Цена блюда', max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='food_energy',
            field=models.DecimalField(decimal_places=2, help_text='Обязательное. Калорийность ингредиента', max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Обязательное. Название ингредиента', max_length=128),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(help_text='Обязательное. Адрес заведения', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, help_text='Средняя цена в заведении', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(help_text='Время закрытия заведения', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dishes',
            field=models.ManyToManyField(help_text='Обязательное. Список блюд', to='restaurants.Dish'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(help_text='Обязательное. Название заведения', max_length=64),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(help_text='Время открытия заведения', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(help_text='Владелец заведения', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(help_text='Фотография заведения', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='point',
            field=models.ForeignKey(blank=True, help_text='Координаты заведения', null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Point'),
        ),
    ]
