# Generated by Django 3.0.8 on 2020-08-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_auto_20200807_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_calories',
            field=models.DecimalField(decimal_places=2, help_text='Калорийность блюда', max_digits=7, null=True),
        ),
    ]
