# Generated by Django 3.0.8 on 2020-08-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_auto_20200807_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(help_text='Список ингредиентов блюда', to='restaurants.Ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(help_text='Название блюда', max_length=128),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена блюда', max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='food_energy',
            field=models.DecimalField(decimal_places=2, help_text='Калорийность ингредиента', max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Название ингредиента', max_length=128),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(help_text='Адрес заведения', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dishes',
            field=models.ManyToManyField(help_text='Список блюд', to='restaurants.Dish'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(help_text='Название заведения', max_length=64),
        ),
    ]
